### PR TITLE
Add Cypress CYALKIT-E02 Beacon Support

### PR DESCRIPTION
**Pull request by darkskiez**
These beacons emit iBeacon like frames, but the Minor ID
contains the temperature and humidity values.

### CODE REVIEW

**Comment by darkskiez** [comment]
This is related to and fixes #7

**Comment by citruz** [comment]
Awesome, thanks for the PR!
The code changes look good, but why did you add Google to the License? Did you submit this on behalf of Google?

**Comment by darkskiez** [comment]
Yes I did. I can easily contribute opensource patches outside of work time
without filling in forms asking for permission if they retain the copyright
and it's under an approved oss license. Is that ok?

**Comment by citruz** [comment]
I would prefer not to give Google the copyright of my project. How about we change the line to 

> Copyright 2017 Felix Seele and contributors listed in CONTRIBUTORS.txt

and in that file, we list everyone who contributed to the project and you can add what you want/need there.

**Comment by darkskiez** [comment]
I checked, Authors files are compliant with the policy. So sounds good to
me.

**Comment by citruz** [comment]
Awesome. What should I add to CONTRIBUTORS.md?

**Comment by darkskiez** [comment]
- darkskiez (https://github.com/darkskiez) Google LLC

I think should cover it.. Thanks!

Now to glue it into home assistant :)

**Comment by citruz** [comment]
1.2.0 is live on PyPi. Sorry for the slight delay. 
If you want to integrate Cypress beacons, you will need to create a new component because the current one only supports the Eddystone beacon format. The configuration parameters are completely different, therefore I think it does not make sense to _somehow_ add Cypress support. It would be cleaner to create a new component specifically for that class of beacons.

**Pull request merged**
