### PR TITLE
Cjmonitor

### PR DESCRIPTION
**Pull request by clydebarrow**
Added support for another environmental monitoring beacon - Control-J Monitor.

### CODE REVIEW

**Comment by citruz** [comment]
Looks great, thank you for your contribution!
Do you have a link to a product page or spec sheet? I can't find anything.

**Comment by clydebarrow** [comment]
Not at present - it's not yet publicly available, the device is in field trials right now. 


Board image

**Comment by citruz** [comment]
Looking over the PR a second time I realized that you did not use the existing structures to parse tag-length-value packets even though your beacon uses this scheme.
Can you please change your code to use the `parse_ltv_packet` method? To identify your beacon type, the `MORE_SERVICE_UUIDS_DATA_TYPE` frame looks like a good candidate.

**Comment by citruz** [comment]
I merged #35 and #36 and refactored all beacon definitions to use the generic ltv parser. The tests look fine, but since I don't have the hardware at hand, I cannot test the actual scanner.
Please verify that I didn't break anything during refactoring by checking out the release1.4.0 branch. As soon as you confirm that everything works as expected, I will finalize the release.
Thanks!

**Comment by clydebarrow** [comment]
Yes, it all works on the hardware. Thanks.

**Pull request merged**
