### PR TITLE
Add Eddystone EID frame support

### PR DESCRIPTION
**Pull request by miek**

### CODE REVIEW

**Comment by citruz** [comment]
Thanks for your contribution, looks really good! I will test this later in the day.
Could you please fix the two lint errors so that travis is happy? :wink:

**Comment by miek** [comment]
I've fixed the long line lint error, but fixing the too-many-returns one would require restructuring the whole function - not sure what to do there.

**Comment by citruz** [comment]
Ah I see. You should be able to silence the warning by putting 
`# pylint: disable=too-many-return-statements`
at the top of the file.

**Comment by citruz** [comment]
I merged your commit and pushed the new version to PyPI. Thanks for the contribution!

**Pull request merged**
